
all: Makefile
	$(MAKE) libmxmlev.a

install: Makefile
	$(MAKE) install-libmxmlev.a
%: Makefile
	$(MAKE) $*

Makefile: configure Makefile.in.at
	./configure --prefix=`readline -f $(INSTALL_DIR)` --disable-threads
	mv Makfile.in.at Makefile.in

configure: configure.ac Makefile.in.at
	rm -rf m4
	mkdir m4
	-autoreconf -fi


Makefile.in.at: Makefile.in.orig
	-mv Makefile.in Makefile.in.at
	cp Makefile.in.orig Makefile.in

